### ISSUE TITLE
Figure out how to run node packages as standalone commands

### ISSUE THREAD

**Issue by 123aswin123** [123aswin123/vedi#1]
https://github.com/SimbCo/httpster/blob/master/package.json has some pointers.

``` shell
sayhi Laksh
```

should produce the output

``` shell

Hello Laksh

````

**Comment by Laksh47** [comment]
```
➜  timebomb git:(stand_alone_npm_pkg) node .     
➜  timebomb git:(stand_alone_npm_pkg) ✗ node . test
test
➜  timebomb git:(stand_alone_npm_pkg) ✗ node . wow 
wow
➜  timebomb git:(stand_alone_npm_pkg) ✗ 

```

**Comment by Laksh47** [comment]
@123aswin123 @shivasurya 

➜  timebomb git:(stand_alone_npm_pkg) ✗ sudo npm install -g .
/usr/local/bin/timebomb -> /usr/local/lib/node_modules/timebomb/index.js
+ timebomb@0.1.0
updated 1 package in 0.067s
➜  timebomb git:(stand_alone_npm_pkg) ✗ timebomb
➜  timebomb git:(stand_alone_npm_pkg) ✗ timebomb testing
testing
➜  timebomb git:(stand_alone_npm_pkg) ✗ sudo npm uninstall -g timebomb
removed 1 package in 0.053s
➜  timebomb git:(stand_alone_npm_pkg) ✗
